/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        accent: {
          50: 'var(--accent-50)',
          400: 'var(--accent-400)',
          500: 'var(--accent-500)',
          600: 'var(--accent-600)',
          900: 'var(--accent-900)',
        },
        ink: 'var(--ink)',
        steel: 'var(--steel)',
        signal: 'var(--signal)',
        mint: 'var(--mint)',
        'mint-soft': 'var(--mint-soft)',
        semantic: {
          success: 'var(--semantic-success)',
          warning: 'var(--semantic-warning)',
          danger: 'var(--semantic-danger)',
          info: 'var(--semantic-info)',
        },
        background: 'var(--bg-base)',
        surface: 'var(--bg-surface)',
        'surface-container': 'var(--bg-elevated)',
        'surface-container-low': 'var(--bg-elevated)',
        'surface-container-lowest': 'var(--bg-surface)',
        'surface-container-high': 'var(--bg-subtle)',
        'surface-container-highest': 'var(--bg-subtle)',
        'surface-variant': 'var(--bg-subtle)',
        'on-surface': 'var(--text-primary)',
        'on-surface-variant': 'var(--text-secondary)',
        'on-background': 'var(--text-primary)',
        outline: 'var(--text-muted)',
        'outline-variant': 'var(--border-color)',
        primary: 'var(--accent-600)',
        'primary-container': 'var(--accent-500)',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        secondary: 'var(--mint)',
        'secondary-container': 'var(--mint-soft)',
        'on-secondary': '#064033',
        'on-secondary-container': '#064033',
        tertiary: 'var(--info)',
        'tertiary-container': 'color-mix(in srgb, var(--info) 16%, white)',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#0c4a6e',
        error: 'var(--danger)',
        'error-container': 'color-mix(in srgb, var(--danger) 14%, white)',
        'on-error': '#ffffff',
        'on-error-container': '#7f1d1d',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'JetBrains Mono', 'monospace'],
        'body-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'data-mono': ['IBM Plex Mono', 'monospace'],
        'label-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.875rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-desktop': '1.25rem',
        margin: '1.25rem',
        gutter: '1rem',
        'space-2xs': '0.25rem',
        'space-xs': '0.375rem',
        'margin-desktop': '1.75rem',
        'space-xl': '1.75rem',
        'space-md': '0.875rem',
        'space-lg': '1.25rem',
        'space-2xl': '2.5rem',
        'space-sm': '0.5rem',
        rail: '88px',
      },
      fontSize: {
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-xl': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'label-md': ['11px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-lg': ['22px', { lineHeight: '30px', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-lg': ['13px', { lineHeight: '18px', fontWeight: '600' }],
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-sm': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
      },
      keyframes: {
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.55s cubic-bezier(0.22, 1, 0.36, 1) both',
      },
    },
  },
  plugins: [],
}
